export const SAVE_AUTHORS = 'SAVE_AUTHORS';
export const CREATE_AUTHOR = 'CREATE_AUTHOR';
export const ADD_COURSE_AUTHOR = 'ADD_COURSE_AUTHOR';
export const REMOVE_COURSE_AUTHOR = 'DELETE_COURSE_AUTHOR';
export const RESET_COURSE_AUTHORS = 'RESET_COURSE_AUTHORS';
